spring.application.name=CRM-Backend
spring.datasource.url=jdbc:mysql://localhost:3306/crm
spring.datasource.username=root
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
jwt.secret=lkjhfdsadfghjklpoiuytrewq0987654321
jwt.expiration=86400000
