spring.application.name=CRM-Backend
spring.datasource.url=database-2.cza6ise4wo9y.ap-south-1.rds.amazonaws.com/sample
spring.datasource.username=admin
spring.datasource.password = rahul1234
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
jwt.secret=lkjhfdsadfghjklpoiuytrewq0987654321
jwt.expiration=86400000
